#!/bin/bash
EXTENSION_NAME="eZ Find"
EXTENSION_IDENTIFIER="ezfind"
EXTENSION_SUMMARY="eZ Find search plugin for eZ Publish"
EXTENSION_LICENSE="GPL"
EXTENSION_VERSION="2.1"
EXTENSION_PUBLISH_VERSION="4.2"
EXTENSION_ARCHIVE_NAME="ezfind"
EXTENSION_PHP_VERSION="5.2"
